# Generated by Django 2.2.5 on 2020-02-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pose_model',
            name='pose_array',
            field=models.TextField(blank=True, null=True),
        ),
    ]
